server:
  port: 6798
  servlet:
    context-path: /dbExport
spring:
  application:
    name: db-export
  thymeleaf:
    cache: false
    charset: UTF-8
    template-loader-path: classpath:/templates/
    prefix: classpath:/templates/thymeleaf/
    suffix: .html
    mode: HTML5
    encoding: UTF-8

word:
  model:
    export: D://export.docx
    import: D://dbmodel//import.docx
    sub-model: D://dbmodel//sub_model.docx